---
- name: Install and configure fail2ban
  hosts: server_web
  become: yes
  tasks:
    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Ensure fail2ban service is started and enabled
      systemd:
        name: fail2ban
        state: started
        enabled: yes

    - name: Configure fail2ban
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime  = 10m
          findtime  = 10m
          maxretry  = 5
          ignoreip  = 127.0.0.1/8 ::1

          [sshd]
          enabled   = true
          port      = ssh
          filter    = sshd
          logpath   = /var/log/auth.log
          backend   = systemd
        mode: '0644'

    - name: Restart fail2ban to apply new configuration
      systemd:
        name: fail2ban
        state: restarted

    - name: Ensure ufw allows SSH on port 2020
      ufw:
        rule: allow
        port: 2020
        proto: tcp


    - name: Update SSH port to 2020 in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port '
        line: 'Port 2020'
        state: present

    - name: Restart SSH service to apply port change
      systemd:
        name: ssh
        state: restarted


    - name: Add user supports to sudo group
      user:
        name: supports
        groups: sudo
        append: yes

    - name: Update SSH configuration in /etc/ssh/sshd_config
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Port 33133
          LogLevel INFO
          PermitRootLogin no
          StrictModes yes
          MaxAuthTries 3
          MaxSessions 6
          PermitEmptyPasswords no
          AllowTcpForwarding no
          X11Forwarding no
          ClientAliveInterval 180
        create: yes


    - name: Backup existing sources.list
      command: cp /etc/apt/sources.list /etc/apt/sources.list.bak
      changed_when: false

    - name: Remove existing repositories
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb '
        state: absent

    - name: Add new repositories
      blockinfile:
        path: /etc/apt/sources.list
        block: |
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble main restricted universe multiverse
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble-updates main restricted universe multiverse
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble-security main restricted universe multiverse
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble-backports main restricted universe multiverse
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble-proposed main restricted universe multiverse
        create: yes

    - name: Update package index
      apt:
        update_cache: yes
