---
- name: Install aplikasi
  hosts: server_web
  become: yes
  tasks:
    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Run Docker installation script
      command: bash /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Java 1.8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install Apache Ant
      apt:
        name: ant
        state: present

    - name: Download and Install Apache Tomcat
      block:
        - name: Download Tomcat
          get_url:
            url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.tar.gz
            dest: /tmp/apache-tomcat-9.0.73.tar.gz

        - name: Extract Tomcat
          unarchive:
            src: /tmp/apache-tomcat-9.0.73.tar.gz
            dest: /opt/
            remote_src: yes

        - name: Create symlink for Tomcat
          file:
            src: /opt/apache-tomcat-9.0.73
            path: /opt/tomcat
            state: link

        - name: Set environment variables for Tomcat
          lineinfile:
            path: /etc/environment
            line: "CATALINA_HOME=/opt/tomcat"
            create: yes

        - name: Create systemd service file for Tomcat
          copy:
            dest: /etc/systemd/system/tomcat.service
            content: |
              [Unit]
              Description=Apache Tomcat Web Application Container
              After=network.target

              [Service]
              Type=forking
              User=root
              Group=root
              Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
              Environment=CATALINA_HOME=/opt/tomcat
              Environment=CATALINA_BASE=/opt/tomcat
              ExecStart=/opt/tomcat/bin/startup.sh
              ExecStop=/opt/tomcat/bin/shutdown.sh
              Restart=on-failure

              [Install]
              WantedBy=multi-user.target

        - name: Reload systemd
          systemd:
            daemon_reload: yes

        - name: Enable and start Tomcat service
          systemd:
            name: tomcat
            state: started
            enabled: yes

    - name: Install Apache HTTP Server
      apt:
        name: nginx
        state: present


    - name: Allow port 8080/tcp through UFW
      ufw:
        rule: allow
        name: '8080/tcp'

    - name: Allow port 80/tcp through UFW
      ufw:
        rule: allow
        name: '80/tcp'
