---
- name: Configuration Fresh Install
  hosts: server_web
  become: yes
  tasks:
    - name: Setup Timezone
      timezone:
        name: Asia/Jakarta

    - name: Backup existing sources.list
      command: cp /etc/apt/sources.list /etc/apt/sources.list.bak
      changed_when: false

    - name: Add new repositories
      blockinfile:
        path: /etc/apt/sources.list
        block: |
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble main restricted universe multiverse
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble-updates main restricted universe multiverse
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble-security main restricted universe multiverse
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble-backports main restricted universe multiverse
          deb http://cdn.repo.cloudeka.id/ubuntu/ noble-proposed main restricted universe multiverse
        create: yes

    - name: Update package index
      apt:
        update_cache: yes

    - name: Install required standart packages
      apt:
        name:
          - curl
          - wget
          - git
          - nano
          - net-tools
          - htop
          - logcheck
          - logwatch
          - fail2ban
        state: present
        update_cache: yes


#    - name: Disable IPv6 with sysctl
#      ansible.posix.sysctl:
#        name: "{{ item }}"
#        value: "1"
#        state: "present"
#        reload: "yes"
#      with_items:
#        - net.ipv6.conf.all.disable_ipv6
#        - net.ipv6.conf.default.disable_ipv6
#        - net.ipv6.conf.lo.disable_ipv6


    - name: Disable IPv6 in sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        state: present
        regexp: '^#?net.ipv6.conf.all.disable_ipv6'
        line: 'net.ipv6.conf.all.disable_ipv6 = 1'

    - name: Disable IPv6 in all interfaces
      lineinfile:
        path: /etc/sysctl.conf
        state: present
        regexp: '^#?net.ipv6.conf.default.disable_ipv6'
        line: 'net.ipv6.conf.default.disable_ipv6 = 1'

    - name: Disable IPv6 in sysctl.d
      copy:
        content:
          net.ipv6.conf.all.disable_ipv6 = 1
          net.ipv6.conf.default.disable_ipv6 = 1
        dest: /etc/sysctl.d/99-disable-ipv6.conf

    - name: Reload sysctl
      command: sysctl -p

    - name: Create group infra
      group:
        name: infra
        state: present

    - name: Add user and add group
      user:
        name: sri
        password: "{{ '1234' | password_hash('sha512') }}"
        groups: infra,sudo
        shell: /bin/bash
        state: present


    - name: Set password expiration for user arief
      command: chage -M 90 -W 15 sri


    - name: Create /var/log/user-activity directory
      file:
        path: /var/log/user-activity
        state: directory
        owner: root
        group: root
        mode: '1777'

    - name: Ensure /etc/bash.bashrc exists
      file:
        path: /etc/bash.bashrc
        state: touch

    - name: Append logging script to /etc/bash.bashrc
      blockinfile:
        path: /etc/bash.bashrc
        block: |
          PROMPT_COMMAND='current_date=$(date "+%Y-%m-%d"); mkdir -p /var/log/user-activity; logfile="/var/log/user-activity/$(whoami)-${current_date}.log"; echo "$(date "+%Y-%m-%d %H:%M:%S") $(whoami)  ${SSH_CLIENT%% *} $(history 1 | sed "s/^[ ]*[0-9]\+[ ]*//")" >> "$logfile"'


    - name: Set permissions on new log files
      find:
        paths: /var/log/user-activity
        recurse: yes
        file_type: file
      register: log_files

    - name: Set file permissions for new log files
      file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: '0640'
      loop: "{{ log_files.files }}"
