---
- name: Set timezone to Asia/Jakarta
  hosts: server_web
  become: yes
  tasks:
    - name: Ensure the correct timezone is set
      timezone:
        name: Asia/Jakarta

    - name: Add user budi with password 123 and set password expiration
      user:
        name: budi
        password: "{{ '123' | password_hash('sha512') }}"
        state: present
    - name: Set password expiration for user budi
      command: chage -M 90 -W 15 budi

    - name: Add user caca with password 222 and set password expiration
      user:
        name: caca
        password: "{{ '222' | password_hash('sha512') }}"
        state: present
    - name: Set password expiration for user caca
      command: chage -M 90 -W 15 caca

    - name: Install required packages
      apt:
        name:
          - curl
          - wget
          - git
        state: present
        update_cache: yes

    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: "present"
        reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    - name: Debian | blacklist ipv6 in modprobe
      ansible.builtin.lineinfile:
        dest: /etc/modprobe.d/blacklist.conf
        line: 'blacklist ipv6'
        mode: '0644'
        create: true
      notify:
        - Rmmodipv6

    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Run Docker installation script
      command: bash /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Ensure /var/log/user-activity directory exists
      file:
        path: /var/log/user-activity
        state: directory
        mode: '0755'

    - name: Configure user activity logging in /etc/bash.bashrc
      lineinfile:
        path: /etc/bash.bashrc
        state: present
        create: yes
        line: |
          PROMPT_COMMAND='current_date=$(date "+%Y-%m-%d"); \
          logfile="/var/log/user-activity/$(whoami)-${current_date}.log"; \
          echo "$(date "+%Y-%m-%d %H:%M:%S") $(whoami) ${SSH_CLIENT%% *} $(history 1 | sed "s/^[ ]*[0-9]\+[ ]*//")" >> "$logfile"'

    - name: Create script to list users and password expiration dates
      copy:
        dest: /usr/local/bin/list_user_expiration.sh
        content: |
          #!/bin/bash
          echo "User Password Expiration Dates:"
          for user in $(cut -f1 -d: /etc/passwd); do
            chage -l $user | grep "Password expires" | awk -v user=$user '{print user": "$4" "$5" "$6}'
          done
        mode: '0755'

    - name: Ensure list_user_expiration.sh is executable
      file:
        path: /usr/local/bin/list_user_expiration.sh
        mode: '0755'
        state: file
